### PR TITLE
Community board options are displayed for Picos

### LINKED ISSUE #1706: Community board options are not displayed for Picos
**Describe the bug**
For picos, the community board options don't show.

**Steps To Reproduce**
1. Start MobiFlight
2. Connect a pico without MobiFlight firmware
3. Go to the Mobiflight settings
4. Update firmware and try to select one of the community board options
5. See error

**Expected behavior**
We should see different partner board and community board options that ship with MobiFlight

**Actual behavior**
We don't see these options.

**Details**
 - MobiFlight Version: 10.1

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #1706 

This fix added a new method to get a list of all matches by UsbDriveLabel.

image

### CODE REVIEW

File: MobiFlight/BoardDefinitions.cs [hunk 1]
```diff
@@ -33,6 +33,18 @@ public static Board GetBoardByUsbVolumeLabel(String volumeLabel)
             return boards.Find(board => board.UsbDriveSettings?.VolumeLabel == volumeLabel);
         }
 
+        /// <summary>
+        /// Finds board definitions by matching against USB drive volume label. This does not check for the
+        /// presence of a secondary file on the drive to confirm it is a supported USB drive.
+        /// This is used for offering different community board options.
+        /// </summary>
+        /// <param name="volumeLabel">The volume label to match</param>
+        /// <returns>The first board definition matching the volumeLabel, or null if none found.</returns>
```
Comment (neilenns) [inline MobiFlight/BoardDefinitions.cs:42]: This needs to be updated to say it returns all board definitions matching the volumeLabel.

**Review by neilenns — CHANGES_REQUESTED** [review]
One minor thing
