### PR TITLE
Fixing wrong placeholders in string

### LINKED ISSUE #1139: WMI log messages have extra $ in them
Oops. Someone did string interpolation the typescript way instead of the C# way.

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #1139 

All placeholders in the $"" string that had a format of `${myVar}` were replaced by `{myVar}`.

### CODE REVIEW

**Comment by neilenns** [comment]
Also fixes #1139

**Review by neilenns — APPROVED** [review]

File: SimConnectMSFS/SimConnectCache.cs [hunk 1]
```diff
@@ -223,8 +223,6 @@ internal void Start()
 
         private void SimConnectCache_OnRecvClientData(SimConnect sender, SIMCONNECT_RECV_CLIENT_DATA data)
         {
-
```
Comment (DocMoebiuz) [inline SimConnectMSFS/SimConnectCache.cs:226]: I have no idea why this sneaked in, because I review all files individually.

Comment (neilenns) [reply SimConnectMSFS/SimConnectCache.cs:226]: Oops
