### PR TITLE
Prevent exception by ensuring thread-safe access to updatedValues dictionary

### LINKED ISSUE #2324: MobiFlight throws Exception because of concurrent access to Collection
**Describe the bug**
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MobiFlight.ExecutionManager.FrontendUpdateTimer_Execute(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Expected behavior**
MobIFlight should be robust for concurrent access to the `updatedValues` dictionary

**Actual behavior**
It can throw an exception

**Details**
 - MobiFlight Version: 10.5.3.x (BETA)

**Additional context**
[Discord post](https://discord.com/channels/608690978081210392/635953880122785824/1411604295639371868)

### PR DESCRIPTION
**Pull request by Leonscape**
The `updatedValues` is now using `ConcurrentDictionary` and we don't have to worry about access from different threads anymore.

- [x] Use ConcurrentDictionary
- [x] Update unit-tests

fixes #2324

### CODE REVIEW

File: MobiFlight/Execution/ConfigItemExecutor.cs [hunk 1]
```diff
@@ -71,7 +72,7 @@ public void Execute(OutputConfigItem cfg, Dictionary<string, IConfigItem> update
                 cfg.Status[ConfigItemStatusType.Test] = "TESTING";
                 if (!cfg.Equals(originalCfg))
                 {
-                    updatedValues[cfg.GUID] = cfg;
+                    updatedValues.AddOrUpdate(cfg.GUID, cfg, (k,o) => cfg);
```
Comment (DocMoebiuz) [inline MobiFlight/Execution/ConfigItemExecutor.cs]: What's the reason that you decided to use AddOrUpdate instead of the index setter access?

File: MobiFlight/ExecutionManager.cs [hunk 2]
```diff
@@ -249,12 +250,14 @@ private void FrontendUpdateTimer_Execute(object sender, EventArgs e)
...
-            lock (updatedValues)
+            foreach (var kvp in updatedValues)
             {
-                list = updatedValues.Values.Select(cfg => new ConfigValueOnlyItem(cfg)).Cast<IConfigValueOnlyItem>().ToList();
-                updatedValues.Clear();
+                if (updatedValues.TryRemove(kvp.Key, out var value))
+                {
+                    list.Add(new ConfigValueOnlyItem(value));
+                }
             }
```
Comment (DocMoebiuz) [inline MobiFlight/ExecutionManager.cs]: I would have expected the following works:

```
var list = updatedValues.Values.Select(cfg => new ConfigValueOnlyItem(cfg)).Cast<IConfigValueOnlyItem>().ToList();
updatedValues.Clear();
````

File: MobiFlight/ExecutionManager.cs [hunk 3]
```diff
@@ -1207,7 +1210,7 @@ void mobiFlightCache_OnButtonPressed(object sender, InputEventArgs e)
                 }
             }
 
-            updatedInputValues.Keys.ToList().ForEach(k => this.updatedValues[k] = updatedInputValues[k]);
+            updatedInputValues.Keys.ToList().ForEach(k => updatedValues.AddOrUpdate(k, updatedInputValues[k], (ck,o) => updatedInputValues[ck]));
```
Comment (DocMoebiuz) [inline MobiFlight/ExecutionManager.cs]: the original style should still work without any modifications.

File: MobiFlight/ExecutionManager.cs [hunk 4]
```diff
@@ -1240,7 +1243,7 @@ private void UpdateInputPreconditions()
 
                         if (!cfg.Status.SequenceEqual(originalCfg.Status))
                         {
-                            updatedValues[cfg.GUID] = cfg;
+                            updatedValues.AddOrUpdate(cfg.GUID, cfg, (k, o) => cfg);
```
Comment (DocMoebiuz) [inline MobiFlight/ExecutionManager.cs]: the original way would just work, in my opinion the benefit is: it is simple and clear to read, no lambda.

File: MobiFlight/Execution/ConfigItemExecutor.cs (hunk 1 above)
Comment (DocMoebiuz) [reply MobiFlight/Execution/ConfigItemExecutor.cs]: Same for all the subsequent changes.
I would prefer the old direct way which is easy to read.

File: MobiFlight/ExecutionManager.cs (hunk 2 above)
Comment (Leonscape) [reply MobiFlight/ExecutionManager.cs]: updateValues.Values is a snapshot of the values of the dictionary which is then iterated by the select.
Any added items after the snapshot would not be processed, but would then be removed by the Clear.

So by doing it through the remove we know the item is added to list to be processed. We may leave some values to be processed on the next call.

Theres also wrapping in a count > 0, to guarentee emptying the dictionary, but if lots of things are being added that can cause a delay. or even infinite looping (had that) so a limit on the outer loop is also really needed.

File: MobiFlight/ExecutionManager.cs (hunk 3 above)
Comment (Leonscape) [reply MobiFlight/ExecutionManager.cs]: This is part of my current work place policy, So concurrent setting is always AddOrUpdate. Just me doing the automatically, its not really necessary here. i've changed it back.

File: MobiFlight/ExecutionManager.cs (hunk 4 above)
Comment (Leonscape) [reply MobiFlight/ExecutionManager.cs]: See previous comment changed them back.

File: MobiFlight/Execution/ConfigItemExecutor.cs (hunk 1 above)
Comment (Leonscape) [reply MobiFlight/Execution/ConfigItemExecutor.cs]: Changed it back got a little carried away, Its required where I work for ConcurrentDictionaries, I think mainly to show its a concurrent. I've reverted it.

File: MobiFlight/ExecutionManager.cs (hunk 2 above)
Comment (DocMoebiuz) [reply MobiFlight/ExecutionManager.cs]: Then let us use the best of both worlds

```
// now we can itereate over the it and remove the keys safely
updatedValues.Keys.ToList().ForEach(key => {
  if (!updatedValues.TryRemove(key, out var value)) return;
  list.Add(new ConfigValueOnlyItem(value))
})

ToList() really creates a copy of the keys and would have its own stable enumerator.

Comment (DocMoebiuz) [reply MobiFlight/ExecutionManager.cs]: I always try to implement early returns instead of nested blocks.

Comment (Leonscape) [reply MobiFlight/ExecutionManager.cs]: Made the change.

File: MobiFlight/ExecutionManager.cs [hunk 5]
```diff
@@ -248,13 +249,15 @@ private void FrontendUpdateTimer_Execute(object sender, EventArgs e)
...
+            updatedValues.Keys.ToList().ForEach(key =>
             {
-                list = updatedValues.Values.Select(cfg => new ConfigValueOnlyItem(cfg)).Cast<IConfigValueOnlyItem>().ToList();
-                updatedValues.Clear();
-            }
+                if(!updatedValues.TryRemove(key, out var value))
+                    return;
+
+                list.Add(new ConfigValueOnlyItem(value));
+            });
```
[the remark this answers is not in the document]
Comment (Leonscape) [reply MobiFlight/ExecutionManager.cs:261]: Not a race the behaviour we want.
