### PR TITLE
Initialize Log Levels correctly in ComboBox in Settings dialog

### LINKED ISSUE #954: ArgumentNullException when closing the settings dialog with no log level selected
**Describe the bug**
A user in Discord reported an unhandled ArgumentNullException when closing the settings dialog. Somehow the user was in a state where no log level was selected in the dropdown. MobiFlight version 9.5.0.

```
System.ArgumentNullException: Değer null olamaz.
Parametre adı: value
   konum: System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   konum: System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   konum: MobiFlight.UI.Panels.Settings.GeneralPanel.saveSettings()
   konum: MobiFlight.UI.Dialogs.SettingsDialog.saveSettings()
   konum: MobiFlight.UI.Dialogs.SettingsDialog.okButton_Click(Object sender, EventArgs e)
```

We haven't been able to reproduce this but it's clearly something that can happen.

Seems to be related to this code in GeneralPanel.cs: https://github.dev/MobiFlight/MobiFlight-Connector/blob/26cd05ffdcaa82d6fe47d27fcb48336bc6b2b767/UI/Panels/Settings/GeneralPanel.cs#L83-L87

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #954 

- [x] DropDown has list of log levels as data source
- [x] item is selected on 1st based on the default settings ("Info")
- [x] there is no empty selection option

### CODE REVIEW

File: UI/Panels/Settings/GeneralPanel.cs [hunk 1]
```diff
@@ -30,13 +35,31 @@ public void loadSettings()
             languageComboBox.DisplayMember = "Label";
             languageComboBox.ValueMember = "Value";
             languageComboBox.SelectedIndex = 0;
+        }
 
+        protected void InitializeLogLevelComboBox()
+        {
+            List<ListItem> LogLevels = new List<ListItem>();
```
Comment (neilenns) [inline UI/Panels/Settings/GeneralPanel.cs:42]: this can be `var LogLevels = new List<ListItem>();`... if you care.

**Review by neilenns — APPROVED** [review]
