### PR TITLE
Config references can be used with new test mode

### LINKED ISSUE #1499: New test mode has problems with config references.
**Describe the bug**
When modifiers contain config references, then the new interactive test mode doesn't work correctly.

**Steps To Reproduce**
1. Open the ConfigWizard
2. Add a config reference with 'a'
3. Use the config reference in a transform modifier
4. Add an interpolation modifier with values that would cause interpolation
5. Use a sensible test value
6. Start Test Mode
7. See error

**Expected behavior**
All modifiers should be applied

**Actual behavior**
Transform modifiers fails with error because 'a' is not defined.

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #1499 

- [x] Config references now have test values
- [x] Test values are used when in test mode (Config wizard)
- [x] Test values are stored with mcc-file
- [x] Unit tests
- [x] i18n
- [x] documentation (https://github.com/MobiFlight/MobiFlight-Connector/wiki/Mobiflight-Connector-Main-Window#config-references)

### CODE REVIEW

File: Base/ConfigRef.cs [hunk 1]
```diff
@@ -24,6 +24,7 @@ public void ReadXml(XmlReader reader)
             if (reader["active"] != null && reader["active"] != "") Active = bool.Parse( reader["active"]);
             if (reader["ref"] != null && reader["ref"] != "") Ref = reader["ref"];
             if (reader["placeholder"] != null && reader["placeholder"] != "") Placeholder = reader["placeholder"];
+            if (reader["testvalue"] != null && reader["testvalue"] != "") TestValue = reader["testvalue"];
```
Comment (Koseng) [inline Base/ConfigRef.cs:27]: hier könnte man auch `!string.IsNullOrEmpty(reader["testvalue"]) `verwenden

File: UI/Panels/Config/ConfigRefPanelItem.cs [hunk 2]
```diff
@@ -17,6 +17,7 @@ public ConfigRefPanelItem()
         {
             InitializeComponent();
             configRefComboBox.Text = "Select reference";
+            checkBox1.Checked=true;
```
Comment (Koseng) [inline UI/Panels/Config/ConfigRefPanelItem.cs:20]: Missing whitespace
