### PR TITLE
InputShifters save OnHold and OnLongRelease correctly

### LINKED ISSUE #1445: BETA: OnHold and OnLongRelease forget settings on InputShifters
**Describe the bug**
When setting events for OnHold or OnLongRelease, the settings work, but if you go back to the configwizard, the events are empty. They work if they are configured on a regular button input 

**Steps To Reproduce**
1. Go to Inputs tab
2. Add a new configuration item and select a device that is part of an input shifter
3. Set sim events for "On Hold" and "On Long Release"
4. Close configwizard dialog
5. Open the config wizard again

**Expected behavior**
Should remember all settings

**Actual behavior**
Seems that the event settings for On Hold and On Long Release are not being saved when closing
the dialog with "OK".

**Details**
 - MobiFlight Version: 9.7.1.10
 - FlightSim: not relevant
 - AddOn: not relevant

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #1445 

- [x] introduces copy constructor 
- [x] copy constructor is used in clone method
- [x] inputShiftRegister and InputMultiplexer use base copy contructor in Clone() method
- [x] Added unit tests

### CODE REVIEW

File: MobiFlightUnitTests/MobiFlight/InputConfig/ButtonInputConfigTests.cs [hunk 1]
```diff
@@ -19,7 +19,9 @@ public void CloneTest()
             Assert.AreEqual((o.onRelease as JeehellInputAction).EventId, (c.onRelease as JeehellInputAction).EventId, "OnRelease is not correct");
             Assert.AreEqual((o.onLongRelease as MSFS2020CustomInputAction).PresetId, (c.onLongRelease as MSFS2020CustomInputAction).PresetId, "OnLongRelase is not correct");
             Assert.AreEqual((o.onHold as XplaneInputAction).Path, (c.onHold as XplaneInputAction).Path, "onHold is not correct");
+            Assert.AreEqual(o.RepeatDelay, c.RepeatDelay, "RepeatDelay is not correct");
             Assert.AreEqual(o.HoldDelay, c.HoldDelay, "HoldDelay is not correct");
+            Assert.AreEqual(o.LongReleaseDelay, c.LongReleaseDelay, "HoldDelay is not correct");
```
Comment (Koseng) [inline MobiFlightUnitTests/MobiFlight/InputConfig/ButtonInputConfigTests.cs:24]: Should be "LongReleaseDelay....

**Comment by Koseng** [comment]
Great, thanks for fixing. I'm not at home this weekend, cannot test anything.
