### PR TITLE
Hide PWM option for output shift register

### LINKED ISSUE #1291: LED Output config on shift register ports allows PWM option
**Describe the bug**
A user reported in Discord that the output config wizard 

**Steps To Reproduce**
1. Configure an output shift register device in a board
2. Create output config for one of the output ports
3. Go to display tab and configure the output port on the shift register
4. Note the PWM checkbox is active

image

**Expected behavior**
Output config wizard should not allow PWM setting of individual ports of a shift register.

**Actual behavior**
PWM checkbox in the Display tab is active and can be checked which of course later fails.

**Details**
 - MobiFlight Version: 9.7.1.2
 - FlightSim: 
 - AddOn: 

**Additional context**
None.

### PR DESCRIPTION
**Pull request by neilenns**
Fixes #1291 

Easiest bugfix ever? 🤔

### CODE REVIEW

File: UI/Panels/Output/DisplayShiftRegisterPanel.cs [hunk 1]
```diff
@@ -21,6 +21,7 @@ public DisplayShiftRegisterPanel()
 
             displayPinPanel.SetPorts(new List<ListItem>());
             displayPinPanel.WideStyle = true;
+            displayPinPanel.EnablePWMSelect(false);
```
Comment (DocMoebiuz) [inline UI/Panels/Output/DisplayShiftRegisterPanel.cs:24]: Did you write a unit test?

Comment (neilenns) [reply UI/Panels/Output/DisplayShiftRegisterPanel.cs:24]: Lol. No 😂
