### PR TITLE
Firmware update supports concurrent updates with individual base path

### LINKED ISSUE #1562: FirmwareUpdater doesn't support concurrent execution with specific Community Firmware Path
**Describe the bug**
MobiFlightFirmwareUpdater is a static class and has a static property `FirmwarePath`. This was only the same path for all firmware in the past. With the new Community Folder, the firmware path is specific to every project. When there are concurrent firmware updates, the static property doesn't work anymore.

**Steps To Reproduce**
1. Have two community boards with new firmware
2. Start MobiFlight Connector
3. Confirm the message that you want to update all boards

**Expected behavior**
All boards update with their respective firmware.

**Actual behavior**
An error message that the update failed. The error log shows that one firmware file was not found because it was using the basepath of the other firmware.

**Details**
 - MobiFlight Version: 10.0.2.1

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #1562 

- [x] Remove the static `FirmwarePath` property
- [x] Determine the correct base path for every RunAvrDude

### CODE REVIEW

File: MobiFlight/MobiFlightFirmwareUpdater.cs [hunk 1]
```diff
@@ -132,7 +129,7 @@ public static void RunAvrDude(String port, Board board, String firmwareName)
 
                 var attempts = board.AvrDudeSettings.Attempts != null ? $" -x attempts={board.AvrDudeSettings.Attempts}" : "";
                 string anyCommand =
-                    $@"-C""{Path.Combine(FullAvrDudePath, "etc", "avrdude.conf")}""{verboseLevel}{attempts} -p{board.AvrDudeSettings.Device} -c{board.AvrDudeSettings.Programmer} -P{port} -b{baudRate} -D -Uflash:w:""{FirmwarePath}\{firmwareName}"":i";
+                    $@"-C""{Path.Combine(FullAvrDudePath, "etc", "avrdude.conf")}""{verboseLevel}{attempts} -p{board.AvrDudeSettings.Device} -c{board.AvrDudeSettings.Programmer} -P{port} -b{baudRate} -D -Uflash:w:""{fullFirmwarePath}"":i";
```
Comment (DocMoebiuz) [inline MobiFlight/MobiFlightFirmwareUpdater.cs:132]: this is actually not nice... I'd prefer a dedicated variable for this.

File: MobiFlight/MobiFlightFirmwareUpdater.cs [hunk 2]
```diff
@@ -124,15 +121,17 @@ public static void RunAvrDude(String port, Board board, String firmwareName)
             //verboseLevel = " -v -v -v -v";
 
             // Process() requires an absolute, rather than relative, path when using UseShellExecute = false
-            String FullAvrDudePath = Path.GetFullPath(Path.Combine(ArduinoIdePath, AvrPath));
+            var FullAvrDudePath = Path.GetFullPath(Path.Combine(ArduinoIdePath, AvrPath));
```
Comment (neilenns) [inline MobiFlight/MobiFlightFirmwareUpdater.cs:124]: 🥰

**Review by neilenns — APPROVED** [review]
