### PR TITLE
Prevent the exception when sorting by column header

### LINKED ISSUE #1162: MobiFlight shows exception dialog when user selects last row and then tries to sort the gird view
**Describe the bug**
MobiFlight crashes when user selects last row and then tries to sort the gird view

**Steps To Reproduce**
1. Select the last "empty" line from the gridView
2. Click on any of the column headers for sorting

**Expected behavior**
GridView content is sorted by column values

**Actual behavior**
An exception is thrown.

**Details**
 - MobiFlight Version: [e.g. 8.2.0]
 - FlightSim: [e.g. MSFS2020]
 - AddOn: [e.g. Default Aircraft]

**Additional context**
This problem exists for Output and Input Grid Views

** Suggested fix **
Add `?`

``` C#
DataRow currentRow = (row.DataBoundItem as DataRowView)?.Row;
if (currentRow != null)
   SelectedGuids.Add(currentRow["guid"].ToString());
```

image

### PR DESCRIPTION
**Pull request by DocMoebiuz**
fixes #1162 

- [x] Add `?` to the places where DataBoundItem is access and not yet checked for `null`

### CODE REVIEW

File: UI/Panels/InputConfigPanel.cs [hunk 1]
```diff
@@ -116,10 +116,11 @@ private void inputsDataGridView_CellContentClick(object sender, DataGridViewCell
                     } //if
 
                     InputConfigItem cfg;
-                    DataRow row = null;
                     bool create = false;
+                    DataRow row = (inputsDataGridView.Rows[e.RowIndex].DataBoundItem as DataRowView)?.Row;
```
Comment (neilenns) [inline UI/Panels/InputConfigPanel.cs:120]: I think this should be `var` instead of `DataRow` (style-wise)

Comment (neilenns) [reply UI/Panels/InputConfigPanel.cs:120]: And elsewhere in this PR as well.

**Review by neilenns — APPROVED** [review]

File: UI/Panels/InputConfigPanel.cs (hunk 1 above)
Comment (DocMoebiuz) [reply UI/Panels/InputConfigPanel.cs:120]: I want to keep changes to the  minimum at this point. Thanks for pointing this out though!

Comment (DocMoebiuz) [reply UI/Panels/InputConfigPanel.cs:120]: @neilenns I was thinking about this particular case, and I must say: I cannot easily defer the type of `.Row` and so putting `DataRow` in front of the variable makes that crystal clear.

I also started to use `var` when initializing variables and when it is clear by looking at the right hand side, what data type is used. Makes it shorter and easier to read.

Comment (neilenns) [reply UI/Panels/InputConfigPanel.cs:120]: Went and looked at what MSFT says about this since I was curious: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions.

> Use [implicit typing](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/implicitly-typed-local-variables) for local variables when the type of the variable is obvious from the right side of the assignment, or when the precise type is not important.

Then they say to use the explicit type if it isn't clear from the right side (as you mention above). I guess the question is whether knowing it is a DataRow is important :D
