### PR TITLE
Fixed handling of MultiplexDriver deregistration

### LINKED ISSUE #1105: Crash when initializing a multiplexer
**Describe the bug**
User in Discord reported a crash when attempting to use a multiplexer in version 9.6.0.

```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at MobiFlight.Config.MultiplexerDriver.Initialize(String[] pinNos)
   at MobiFlight.Config.MultiplexerDriver.FromInternal(String value)
```

image

The offending line of code is here:

https://github.dev/MobiFlight/MobiFlight-Connector/blob/b4cf773cef7f5c48de6fb215470f1b299ae3bc44/MobiFlight/Config/MultiplexerDriver.cs#L56-L57

Still not sure *why* this is happening but the code can definitely be tweaked to not crash.

### PR DESCRIPTION
**Pull request by GioCC**
Fixes #1105
Modified:
- Fixed registration calls/reg. counter updates in MultiplexerDriver
- Modified functions to lookup an existing MultiplexDriver in MobiFlightPanel; changed their names to reflect the modified purpose
- Added or corrected a few comments about Multiplexer Driver handling

The first commit contains only code changes; the second commits contains only comments, so it should be easier to review.

### CODE REVIEW

File: MobiFlight/Config/Config.cs [hunk 1]
```diff
@@ -155,6 +155,8 @@ public Config FromInternal(String value, bool throwException = false)
                                 // (in this case InputMultiplexer) will provide them
                                 // Treat the MultiplexerDriver as a regular device (add it to the items list), except it won't be shown in the GUI tree.
                                 Items.Add(multiplexerDriver);
+                            } else {
```
Comment (DocMoebiuz) [inline MobiFlight/Config/Config.cs:160]: I would like to keep the symmetry here with calling .FromInternal() for the MultiplexerDriver.
What stands out to me is that we interact with the `registerClient` method from the outside (here), and the inside (inside FromInternal)

``` C#
// Build multiplexerDriver if none found yet 
if (multiplexerDriver == null) {
    multiplexerDriver = new MobiFlight.Config.MultiplexerDriver();
    Items.Add(multiplexerDriver);
}
// then we can always call 
multiplexerDriver.FromInternal(item + BaseDevice.End);
```

Inside from internal the "registerClient" is called, and the pins can be set, if required (we can do it once, or we can do it every time, it doesn't matter if the config was created through mobiflight the base pins will be the same)

File: MobiFlight/Config/MultiplexerDriver.cs [hunk 2]
```diff
@@ -31,12 +31,8 @@ public bool isInitialized()
 
         public bool registerClient()
         {
-            bool res = false;
-            if (_initCounter > 0) {
-                _initCounter++;
-                res = true;
-            }
-            return res;
+            _initCounter++;
```
Comment (DocMoebiuz) [inline MobiFlight/Config/MultiplexerDriver.cs:34]: This should be a `private` message because this is "inner" state that no one should worry about outside.

File: MobiFlight/Config/MultiplexerDriver.cs [hunk 3]
```diff
@@ -31,12 +31,8 @@ public bool isInitialized()
...
+            return true;
         }
 
         public bool unregisterClient()
```
Comment (DocMoebiuz) [inline MobiFlight/Config/MultiplexerDriver.cs:38]: This should be a `private` message because this is "inner" state that no one should worry about outside.

File: MobiFlight/Config/MultiplexerDriver.cs [hunk 4]
```diff
@@ -109,10 +103,9 @@ override public bool FromInternal(String value)
                 pins[1] = paramList[2];
                 pins[2] = paramList[3];
                 pins[3] = paramList[4];
-                res = Initialize(pins);
-            } else {
-                _initCounter++;
+                res = SetPins(pins);
```
Comment (DocMoebiuz) [inline MobiFlight/Config/MultiplexerDriver.cs:106]: Why not setting the paramList result to the PinSx?

We don't have a logic that checks the pin values coming from the board in any other device either since we can assume that the configs are correct.

We an entirely remove SetPins(pins);

File: UI/Panels/Settings/MobiFlightPanel.cs [hunk 5]
```diff
@@ -335,7 +335,7 @@ private TreeNode mfModulesTreeView_initNode(MobiFlightModuleInfo moduleInfo, Tre
                     // MultiplexerDrivers should not appear in the tree, therefore they are stored in a dictionary 
                     // (by module name) for easy retrieval
                     if(device.Type == DeviceType.MultiplexerDriver) {
-                        moduleMultiplexerDrivers.Add(moduleInfo.Name, device as MobiFlight.Config.MultiplexerDriver);
+                        moduleMultiplexerDrivers.Add(moduleNode.Text, device as MobiFlight.Config.MultiplexerDriver);
```
Comment (DocMoebiuz) [inline UI/Panels/Settings/MobiFlightPanel.cs:339]: What is wrong with moduleInfo.Name?
I know both are the same at this point. What was the intention to change it?

File: MobiFlight/Config/MultiplexerDriver.cs [hunk 6]
```diff
@@ -109,10 +103,9 @@ override public bool FromInternal(String value)
...
             }
+            registerClient();
```
Comment (DocMoebiuz) [inline MobiFlight/Config/MultiplexerDriver.cs:108]: I would say, we make this either called from the outside (not my favorite) or only from here (my favorite)

File: UI/Panels/Settings/MobiFlightPanel.cs [hunk 7]
```diff
@@ -1081,10 +1067,12 @@ private void unregisterMuxClient()
         {
             MobiFlight.Config.MultiplexerDriver multiplexerDriver;
             
-            multiplexerDriver = getModuleMultiplexerDriver();
-            multiplexerDriver.unregisterClient();
-            if (!multiplexerDriver.isInitialized()) {
-                moduleMultiplexerDrivers.Remove(getModuleNode().Name);
+            multiplexerDriver = findModuleMultiplexerDriver(false);
```
Comment (DocMoebiuz) [inline UI/Panels/Settings/MobiFlightPanel.cs:1083]: In general I would propose to rethink about the approach to handle a lot of this MultiplexerDriver logic in the View component.

I would like to handle the unregisterClient Logic inside the Config object.

It seems to me that there is too much knowledge of the Driver required here.

**Review by DocMoebiuz — CHANGES_REQUESTED** [review]
it is hard for me to tell what actual situation or state we are really addressing with all the changes made. How critical is this PR? We have had Multiplexer for a while.

I had created this issue recently: https://github.com/MobiFlight/MobiFlight-Connector/issues/1110

And i think some parts are touching this logic too. 

In any case, please review my other comments.

**Comment by GioCC** [comment]
> it is hard for me to tell what actual situation or state we are really addressing with all the changes made. How critical is this PR? We have had Multiplexer for a while.

As stated in the PR text, issue #1105 (which is incorrectly marked as resolved with a patch that gets rid of the crash but leaves the issue). As for how critical, it's a bug that consistently appears if multiplexer inputs ared added/deleted/readded.

> I had created this issue recently: #1110
> And i think some parts are touching this logic too.

Probably yes, since they refer to the same part of the code. However, this is not the issue I meant to address (nor I even tried to).
 
> In any case, please review my other comments.

File: MobiFlight/Config/Config.cs (hunk 1 above)
Comment (GioCC) [reply MobiFlight/Config/Config.cs]: This would definitely work; calling `MultiplexerDriver.FromInternal()` from here (rather than from `WhateverClient.FromInternal()`) would apparently simplify the code.

The only drawback is that the client should have a method to supply the part of its config string to be passed to `multiplexerDriver.FromInternal()` (in the correct format); therefore I had to add a `GetMultiplexerDriverConfig()` method, any other suggestion welcome.

Unfortunately, this now breaks the symmetry with the creation of the corresponding objects in `MobiFlightPanel`, where the call to `registerClient()` is explicit (there are no methods to hide it in). 

On a related note, I still stand by my opinion that having the Multiplexer driver defined in its own specific configuration line only would be a better choice.
The current situation, besides being dangerous because of the redundant definition of the same object in several places (which is required and assumed - without any enforcement or check in place - to be consistent), also brings to additional needless clutter in the configuration file, which will only get worse if further mux client devices are ever implemented. As for the advantages, I fail to see any, but I'd be glad to see it proven otherwise.
(BTW, the above mentioned `GetMultiplexerDriverConfig()` method would also become unnecessary - another simplification.)

File: MobiFlight/Config/MultiplexerDriver.cs (hunk 2 above)
Comment (GioCC) [reply MobiFlight/Config/MultiplexerDriver.cs:34]: Could you explain why should this be "inner"? (The variable obviously is.)
Un/Registering a new client for the driver is essential to keep count when - in the process of adding/deleting devices - the driver can be invalidated and its pins released; this is obviously an operation that has to be exposed.

File: MobiFlight/Config/MultiplexerDriver.cs (hunk 4 above)
Comment (GioCC) [reply MobiFlight/Config/MultiplexerDriver.cs:106]: > Why not setting the paramList result to the PinSx?

They are shifted by one; once shifted, we already have `SetPins()` available. If the issue is removing the validation check, see next comment;

> We don't have a logic that checks the pin values coming from the board in any other device either since we can assume that the configs are correct.

That's true - but that is also the reason why this bug could be caught in the first place. Maybe it's the other way around, checks could be implemented also in other places given the occasion.
 
> We an entirely remove SetPins(pins);

Do you mean the call or the method? Because it is used when initializing a new driver in the GUI.

File: UI/Panels/Settings/MobiFlightPanel.cs (hunk 5 above)
Comment (GioCC) [reply UI/Panels/Settings/MobiFlightPanel.cs:339]: All other properties here are set using `moduleNode`; exactly because `moduleNode.Text` is the same as `moduleInfo.Name` makes it more logical and less misleading to use it.

File: UI/Panels/Settings/MobiFlightPanel.cs (hunk 7 above)
Comment (GioCC) [reply UI/Panels/Settings/MobiFlightPanel.cs:1083]: Could you elaborate? If I'm not mistaken, the saved/uploaded configuration is sourced from the View component before the corresponding Config object exists; and this latter is rebuilt by reading back the board config. Therefore the driver is created (or deleted) first in the GUI.
In that place, it is required that each new client un/registers itself for the reasons mentioned above; I can't see any useless operation there.
Could you make an example of what the `getModuleMultiplexerDriver()` should do differently (or how it could possibly be removed)?

File: MobiFlight/Config/MultiplexerDriver.cs (hunk 6 above)
Comment (GioCC) [reply MobiFlight/Config/MultiplexerDriver.cs:108]: As mentioned in other replies (https://github.com/MobiFlight/MobiFlight-Connector/pull/1119#discussion_r1097854556), I find it hard to imagine how we could get rid of the explicit call (from the outside) in the GUI; and for consistency I'd also be inclined to "extract" it from here (in the only remaining call from `Config`.)

File: UI/Panels/Settings/MobiFlightPanel.cs (hunk 7 above)
Comment (DocMoebiuz) [reply UI/Panels/Settings/MobiFlightPanel.cs:1083]: let's schedule an interactive coding session and try some stuff. it costs a lot of time to discuss this here

Comment (GioCC) [reply UI/Panels/Settings/MobiFlightPanel.cs:1083]: Agreed, I'd be very happy to. I'll PM you for arrangements.

**Comment by GioCC** [comment]
As I mentioned in a PM, After all, this PR fixes an obvious bug, and it does not change multiplexer handling from the way it already is now.
Therefore, in this sense I see no reason to defer it until a possible refactoring is discussed, agreed and implemented; in the meantime, the fix has to be resynced with the evolving main branch with the danger that it introduces new bugs.

**Comment by GioCC** [comment]
@DocMoebiuz Too much time (and too many commits) have passed since this fix; I'm having a hard time keeping all changes correctly merged.
I'll make one last try, if unsuccessful I'll delete the PR and leave the bug for somebody other to fix.
